// <auto-generated />
namespace Super.SuperMarket.DAl.SQLServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class sa7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sa7));
        
        string IMigrationMetadata.Id
        {
            get { return "202005070247335_sa7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
