// <auto-generated />
namespace Super.SuperMarket.DAl.SQLServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class product : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(product));
        
        string IMigrationMetadata.Id
        {
            get { return "202005071616276_product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
